export type StatusValue = 'Pendente' | 'Confirmado' | 'Nao confirmado' | 'Cancelado' | 'Ativo' | string;
export type ShirtSize = 'PP' | 'P' | 'M' | 'G' | 'GG' | 'XG';
export type AllergyValue = 'SIM' | 'NAO';
export type YesNoValue = 'SIM' | 'NAO';

export interface Inscricao {
  rowIndex: number;
  nome: string;
  email: string;
  status: StatusValue;
  dataCadastro: string;
  telefone: string;
  localidade: string;
  dataNascimento: string;
  idade: string;
  sexo: string;
  tamanhoCamisa: ShirtSize | '';
  alergico: AllergyValue | '';
  tipoAlergia: string;
  nomeSocial: string;
  celular: string;
  nomePai: string;
  nomeMae: string;
  enderecoCompleto: string;
  cidade: string;
  estado: string;
  escola: string;
  turno: string;
  serie: string;
  grau: string;
  jaParticipouEncontro: YesNoValue | '';
  qualEncontroAnterior: string;
  paisFizeramECC: YesNoValue | '';
  batizado: YesNoValue | '';
  primeiraComunhao: YesNoValue | '';
  crismado: YesNoValue | '';
  tocaInstrumento: YesNoValue | '';
  gostaCantar: YesNoValue | '';
  familiaOutraDoutrina: YesNoValue | '';
  quemConvidouEac: string;
  paroquia: string;
  motivoEncontro: string;
  valorContribuicao: string;
  visitadoTioVisitacao: YesNoValue | '';
  desistiu: YesNoValue | '';
}

export interface UpdateInscricaoData {
  nome: string;
  email: string;
  status: StatusValue;
  telefone: string;
  localidade: string;
  dataNascimento: string;
  idade: string;
  tamanhoCamisa: ShirtSize | '';
  alergico: AllergyValue | '';
  tipoAlergia: string;
  nomeSocial: string;
  celular: string;
  nomePai: string;
  nomeMae: string;
  enderecoCompleto: string;
  cidade: string;
  estado: string;
  escola: string;
  turno: string;
  serie: string;
  grau: string;
  jaParticipouEncontro: YesNoValue | '';
  qualEncontroAnterior: string;
  paisFizeramECC: YesNoValue | '';
  batizado: YesNoValue | '';
  primeiraComunhao: YesNoValue | '';
  crismado: YesNoValue | '';
  tocaInstrumento: YesNoValue | '';
  gostaCantar: YesNoValue | '';
  familiaOutraDoutrina: YesNoValue | '';
  quemConvidouEac: string;
  paroquia: string;
  motivoEncontro: string;
  valorContribuicao: string;
  visitadoTioVisitacao: YesNoValue | '';
  desistiu: YesNoValue | '';
}
